"""Shared runtime settings for SigDriftr."""

MIN_ARTICLES_FOR_BASELINE = 30
BASELINE_EMA_ALPHA = 0.8

CONFIDENCE_COVERAGE_WEIGHT = 0.5
CONFIDENCE_BASELINE_WEIGHT = 0.5
CONFIDENCE_ARTICLE_DENOMINATOR = 50

MIN_BRIEF_CONFIDENCE = 0.4
HIGH_BRIEF_CONFIDENCE = 0.7

BANDIT_ALPHA = 0.85
BANDIT_TIME_BUCKET_HOURS = 6
BANDIT_MAX_FEEDS_PER_CRAWL = 4

CRAWL_FETCH_CONCURRENCY = 4
CRAWL_FEED_TIMEOUT_SECONDS = 15
