"""Shared runtime settings for SigDriftr."""

MIN_ARTICLES_FOR_BASELINE = 30
BASELINE_EMA_ALPHA = 0.8

CONFIDENCE_COVERAGE_WEIGHT = 0.5
CONFIDENCE_BASELINE_WEIGHT = 0.5
CONFIDENCE_ARTICLE_DENOMINATOR = 50

MIN_BRIEF_CONFIDENCE = 0.4
HIGH_BRIEF_CONFIDENCE = 0.7
